# Configuration File for Limb Server with Default Values

# SocketData

HOST = "127.0.0.1"
PORT = 6969

# Storage

DB = "./limbserver.db"
LOG = "./limbserver.log"
WRITELOGS = false
PRINTLOGS = true

# Private and Public Key Files for Encryption and Decryption

PUBKEYFILE = "./limbserverpubkey.pem"
PRIVKEYFILE = "./limbserverprivkey.pem"