# Configuration File for Limb Server with Default Values

# SocketData

HOST = "127.0.0.1"
PORT = 6969

# Storage

DB = "./limb.db"
LOG = "./limb.log"

# Private and Public Key Files for Encryption and Decryption

PUBKEYFILE = "./pubkey.pem"
PRIVKEYFILE = "./privkey.pem"